apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsc-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage